# Site settings
title: "Phong + Hue"
description: |
    Our endless love story begins...    

owner: Vi Ho Phong
first_published: 2018
email: vihophong@live.com
baseurl: "/lovestory" # the subpath of your site, e.g. /blog
url: "https://phongandhue.github.io" # the base hostname & protocol for your site

social:
  github: https://github.com/phongandhue/weddingsite.git

# Build settings
markdown: kramdown
